#+TITLE: ORG-STATIC-BLOG

This is my personal fork of Bastian Bechtold's [[https://github.com/bastibe/org-static-blog][org-static-blog]] that I
use to generate the site at [[https://joarvarndt.se][joarvarndt.se]]. Maintaining my own version
allows me to add unnecessary features that "work on my machine" but do
not necessarily have to be very polished or easy to customise. So far
these are some of the changes:

- Adds "edit dates" for when an ~.org~-file was most recently changed in ~git~.
- Adds support for listing publishing dates using the french republican calendar.
- Typographical changes that uses proper curly quotes (~“”~) instead of
  blocky ones (~""~) — like in the tag pages.
- Adds the ~dcap~ class to the first paragraphs to enable dropcaps.
- Supports the ~#+subtitle~ header.
- Automatically wraps elements of org-static-blog-acronyms in a
  small-caps class.

For how I integrate this fork into website generation see the
[[https://joarvarndt.se/website][colophon]].


* LICENSE

Copyright 2015, Bastian Bechtold

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are
met:

1. Redistributions of source code must retain the above copyright
   notice, this list of conditions and the following disclaimer.

2. Redistributions in binary form must reproduce the above copyright
   notice, this list of conditions and the following disclaimer in the
   documentation and/or other materials provided with the
   distribution.

3. Neither the name of the copyright holder nor the names of its
   contributors may be used to endorse or promote products derived
   from this software without specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
"AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
(INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

